sonar.projectKey=devops-cicd-security-platform
sonar.projectName=devops-cicd-security-platform
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Specify which files should be included in the scan
sonar.inclusions=**/*.js,**/*.yml,**/*.yaml,**/*.sh

# Exclude dependencies and unnecessary directories from scan
sonar.exclusions=node_modules/**,artifacts/**,reports/**,.git/**
